Update in settings migration to activity
technicalpoets/producer pull request #35
Opened 2017-09-18 18:54 UTC by rcervantes

2017-09-18 19:04 UTC, NateRickard requested changes

2017-09-18 19:04 UTC, NateRickard commented on Producer/Producer.Droid/Settings/SettingsFragment.cs
> -
@rcervantes we _want_ two lines between each method - don't remove them!

2017-09-18 19:04 UTC, NateRickard commented on Producer/Producer.Droid/Settings/SettingsActivity.cs
> +			.Commit ();
Any reason to do this in code vs using the <fragment> tag in the layout file?

2017-09-18 19:04 UTC, NateRickard commented on Producer/Producer.Droid/Settings/SettingsFragment.cs
> -
Can you remove these changes from the PR?

2017-09-18 19:27 UTC, colbylwilliams reviewed
Nate's comments cover it.  I have nothing additional to add.

2017-09-22 13:44 UTC, NateRickard submitted a review, later dismissed

2017-09-22 13:48 UTC, NateRickard approved these changes
Changes look good

2017-09-22 13:49 UTC, merged